language: python
services: mongodb
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "pypy"

install:
  - "travis_retry pip install --upgrade pip"
  - "travis_retry pip install --upgrade setuptools"
  - "if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install coveralls && export HAS_COVERALLS=1; fi"
  - "travis_retry pip install tox-travis"

script: "tox"

after_success:
  - "if [[ $HAS_COVERALLS ]]; then coveralls; fi"
